name: Check json files
on:
  pull_request:
    branches:
      - main

jobs:
  check_codebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Generate latest json schemas
        run: |
          pnpm generate

      - name: Check for code changes
        id: check_changes
        run: |
          git diff --exit-code || (echo "JSON schemas are stale. Please run `pnpm generate` and commit the results."; exit 1)

      - name: Final check and success
        if: ${{ steps.check_changes.outcome == 'success' }}
        run: echo "JSON schemas are up to date."
